### ISSUE TITLE
Numbers sorting as last

### ISSUE THREAD

**Issue by honzajavorek** [encukou/czech-sort#13]
I tested out the new version and it seems to correctly sort Š! However, it sorts numbers as last. I have no idea whether this is expected behavior or not, because I don't know ČSN 97 6030, but I'm reporting this in case you'd have an idea. Feel free to just close this if this is how we Czechs actually sort 😅 

<img width="841" alt="Screenshot 2023-07-12 at 9 53 21" src="https://github.com/encukou/czech-sort/assets/283441/887af0ae-e08d-4823-bac7-57a73ac5c38e">

**Comment by encukou** [comment]
According to [Wikipedia](https://cs.wikipedia.org/wiki/Abecedn%C3%AD_%C5%99azen%C3%AD),
> Číslice se řadí za všemi písmeny, přičemž se řadí podle své číselné hodnoty, apostrof je ještě za číslicemi.

So, yes, it should be the opposite of what ASCII does.

**Comment by honzajavorek** [comment]
Cool, thanks!
