### ISSUE TITLE
ČSN public?

### ISSUE THREAD

**Issue by honzajavorek** [encukou/czech-sort#4]
I'm reading [this status](https://facebook.com/story.php?story_fbid=10157886893869039&id=109323929038) and wondering if that means the ČSN standard mentioned in the README here now becomes public & accessible? I didn't verify, just posting it here as a suggestion.

**Comment by encukou** [comment]
The status is somewhat clickbaity; nothing is public yet. But thanks for the heads-up!

**Comment by encukou** [comment]
It doesn't look like it'll be public.
