### ISSUE TITLE
Fails on character 'Ł' or 'Ø'

### ISSUE THREAD

**Issue by dark-light-cz** [encukou/czech-sort#5]
Fails if text contains 'Ł' or 'Ø'.

`File "/www/exhibition-backend/exhibitionenv/lib/python3.7/site-packages/czech_sort/impl.py", line 95, in key`
`char_lower, _extra_diacritics = DECOMPOSING_EXTRAS[char]`
`KeyError: 'Ł'`
The problem is in impl.py on line 95, where is `DECOMPOSING_EXTRAS[char]`, but in condition above is mentioned `if char_lower in DECOMPOSING_EXTRAS:`.

I expect that `char_lower` should be used on line 95: `char_lower, _extra_diacritics = DECOMPOSING_EXTRAS[char_lower]`

**Comment by encukou** [comment]
Thanks for letting us know!
Fixed in 1.0.1
